#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🎨 Running format check..."
npm run format:check

echo "🔍 Running type-check..."
npm run type-check

echo "✨ Running lint-staged..."
npx lint-staged